version: "3.0"

scanning-settings:
  max-depth: 6
  exclude: []
  include-files: []
  system:
    targets: []

report:
  dependency-vulnerabilities:
    enabled: true
    auto-ignore-in-report:
      python:
        environment-results: true
        unpinned-requirements: true
      cvss-severity: []
      vulnerabilities:
        67599:
          reason: This vulnerability is disputed. Pip
          expires: "2025-01-01"
        70612:
          reason: Currently suppressing as jinja2 isn't explicitly used. Track closure
          expires: "2024-12-31"

fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
    fail-on-any-of:
      cvss-severity:
        - critical
        - medium
        - high
      exploitability:
        - critical
        - medium
        - high

security-updates:
  dependency-vulnerabilities:
    auto-security-updates-limit:
      - patch
