mqtt:
  username: "#<enter the username for the mqtt broker>"
  password: "#<enter the password for the mqtt broker>"
  #keep all properties commented if SSL configuration is not needed
  tls:
    #ca_certs:  # YOUR/ROOT/CA/PATH" Mandatory for an SSL connection
    #certfile:  # YOUR/DEVICE/CERT/PATH . Optional
    #keyfile:   # YOUR/DEVICE/KEY/PATH. Optional
    #cert_reqs: # Boolean. If None then  ssl.CERT_NONE is used. if True the ssl.CERT_REQUIRED is used.
    # else ssl.CERT_OPTIONAL is used .Optional
    #ciphers:   # Str. specifying which encryption ciphers are allowed for this connection. Optional
    #keyfile_password:   # Str. password used to encrypt your certfile and keyfile. Optional
    #insecure_cert: True # Boolean. Skips hostname checking required for self signed certificates. Optional
graphdb:
  username: "#<enter the username for the graph database>"
  password: "#<enter the password for the graph database>"

historian:
  username: "#<enter the username for the Timescale database>"
  password: "#<enter the password for the Timescale database>"
  sslmode: # optional param. valid values are disable, allow, prefer, require, verify-ca, verify-full
  sslcert: # optional param. specifies the file name of the client SSL certificate
  sslkey: # optional param.specifies the location for the secret key used for the client certificate
  sslrootcert: # optional param. specifies the name of a file containing SSL certificate authority (CA) certificate(s)
  sslcrl: # optional param.specifies the file name of the SSL certificate revocation list (CRL)

kafka:
  config: {
      # mandatory if secure connection is made
      security.protocol: "SASL_SSL",
      sasl.mechanisms: "SCRAM-SHA-256",

      # mandatory if secure connection is made
      sasl.username: "",
      #  mandatory if secure connection is made
      sasl.password: "",

      ssl.cipher.suites: "",
      ssl.curves.list: "",
      ssl.sigalgs.list: "",
      ssl.key.location: "",
      ssl.key.password: "",
      ssl.key.pem: "",
    }
dynaconf_merge: true
