name: Setup UNS Python Environment
description: Setup Python Environment, dependencies and static checks
inputs:
  module:
    description: 'the actual module on which the tests should run. "" empty for all modules'
    required: True
    default: "."

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "poetry"

    - name: Install dependencies
      shell: bash
      run: |
        # change to current directory of module        
        cd ./${{ inputs.module }} 
        python -m pip install --upgrade pip poetry
        poetry install
