mqtt:
  username: "#<enter the username for the mqtt broker>"
  password: "#<enter the password for the mqtt broker>"
  # keep all properties commented if SSL configuration is not needed
  tls:
    #ca_certs:  # YOUR/ROOT/CA/PATH" Mandatory for an SSL connection
    #certfile:  # YOUR/DEVICE/CERT/PATH . Optional
    #keyfile:   # YOUR/DEVICE/KEY/PATH. Optional
    #cert_reqs: # Boolean. If None then  ssl.CERT_NONE is used. if True the ssl.CERT_REQUIRED is used.
    # else ssl.CERT_OPTIONAL is used .Optional
    #ciphers:   # Str. specifying which encryption ciphers are allowed for this connection. Optional
    #keyfile_password:   # Str. password used to encrypt your certfile and keyfile. Optional
    #insecure_cert: True # Boolean. Skips hostname checking required for self signed certificates. Optional

historian:
  username: "#<enter the username for the Timescale database>"
  password: "#<enter the password for the Timescale database>"
  sslmode: # optional param. valid values are disable, allow, prefer, require, verify-ca, verify-full
  sslcert: # optional param. specifies the file name of the client SSL certificate
  sslkey: # optional param.specifies the location for the secret key used for the client certificate
  sslrootcert: # optional param. specifies the name of a file containing SSL certificate authority (CA) certificate(s)
  sslcrl: # optional param.specifies the file name of the SSL certificate revocation list (CRL)

dynaconf_merge: true
