rules:
  quoted-strings:
    quote-type: any
    required: only-when-needed
    check-keys: true
    extra-required: ["[:]"]
    extra-allowed: [".*"]
  key-duplicates: {}
  octal-values:
    forbid-implicit-octal: true
