version: "0.2"
# Suggestions can sometimes take longer on CI machines,
# leading to inconsistent results.
suggestionsTimeout: 5000 # ms
ignoreWords:
  [
    "aarch",
    "aenum",
    "aiomqtt",
    "Aiven",
    "alnum",
    "Ashwin",
    "asyncio",
    "asyncpg",
    "autouse",
    "bitnami",
    "buildx",
    "cafile",
    "certfile",
    "cloudkarafka",
    "Codespaces",
    "compileall",
    "createdb",
    "createrole",
    "createuser",
    "cypher",
    "charliermarsh",
    "DBIRTH",
    "dbuser",
    "DCMD",
    "DDATA",
    "DDEATH",
    "DOCKERHUB",
    "dynaconf",
    "EMQX",
    "fastapi",
    "graphdb",
    "historization",
    "HIVEMQ",
    "hostpath",
    "hypertable",
    "IIOT",
    "integrationtest",
    "IPRANGE",
    "ISMASTER",
    "kafka",
    "k8scluster",
    "keepalive",
    "keyfile",
    "Krishnan",
    "Kubernetes",
    "lastnode",
    "librdkafka",
    "mayastor",
    "metallb",
    "microk8s",
    "MOSQUITTO",
    "mqtt",
    "NBIRTH",
    "NCMD",
    "NDATA",
    "NDEATH",
    "nvmf",
    "openebs",
    "packettypes",
    "paho",
    "PGPASSWORD",
    "ppcle",
    "propertyset",
    "propertysets",
    "proto",
    "protobuf",
    "psql",
    "psycopg",
    "pydantic",
    "pytest",
    "reqs",
    "sasl",
    "SCADA",
    "sparkplugb",
    "sslcert",
    "sslcrl",
    "sslkey",
    "sslmode",
    "sslrootcert",
    "storageclass",
    "Tahu",
    "timescaledb",
    "TIMESTAMPTZ",
    "unifiednamespace",
    "UNNEST",
    "unspublisher",
    "userdata",
    "usermod",
    "uvicorn",
    "venv",
    "VERNEMQ",
    "virtualenv",
    "Waehner",
    "websockets",
    "xdist",
  ]
