version: "0.2"
# Suggestions can sometimes take longer on CI machines,
# leading to inconsistent results.
suggestionsTimeout: 5000 # ms
language: "en-GB,en-US"
dictionaries:
  [
    "en-gb",
    "en_US",
    "softwareTerms",
    "public-license",
    "python",
    "python-common",
    "docker",
    "bash",
    "k8s",
    "computing-acronyms",
    "companies",
    "custom-words",
  ]
# Tell CSpell about your dictionary
dictionaryDefinitions: [
    {
      #The name of the dictionary is used to look it up.
      name: "custom-words",
      #Path to the custom word file. Relative to this `cspell.json` file.
      path: ".cspell-custom-words.txt",
      #Some editor extensions will use `addWords` for adding words to your personal dictionary.
      addWords: true,
    },
  ]
ignorePaths:
  - "**/.gitignore" # Ignore the 'node_modules' directory
  - "**/generated/**"
  - "**/*.proto"
  - "**/images/**"
  - "**/LICENSE.aiohttp"
  - "**/LICENSE.aiomqtt"
  - "**/LICENSE.asynpg"
  - "**/LICENSE.dynaconf"
  - "**/LICENSE.eclipse.tahu.sparkplugb"
  - "**/LICENSE.librdkafka"
  - "**/LICENSE.neo4j-python-driver"
  - "**/LICENSE.paho-mqtt"
  - "**/LICENSE.strawberry-graphql"
  - "**/LICENSE.uvicorn"
  - "**/.trunk/**"
  - ".devcontainer/*"
  - "**/*_cache/**"
