mqtt:
  username: "#<enter the username for the mqtt broker>"
  password: "#<enter the password for the mqtt broker>"
  # spell-checker:disable
  tls:

    # keep all properties commented if SSL configuration is not needed
    #ca_certs:  # YOUR/ROOT/CA/PATH" Mandatory for an SSL connection
    #certfile:  # YOUR/DEVICE/CERT/PATH . Optional
    #keyfile:   # YOUR/DEVICE/KEY/PATH. Optional
    #cert_reqs: # Boolean. If None then  ssl.CERT_NONE is used. if True the ssl.CERT_REQUIRED is used.
    # else ssl.CERT_OPTIONAL is used .Optional
    #ciphers:   # Str. specifying which encryption ciphers are allowed for this connection. Optional
    #keyfile_password:   # Str. password used to encrypt your certfile and keyfile. Optional
    #insecure_cert: True # Boolean. Skips hostname checking required for self signed certificates. Optional
kafka:
  config: {
      #mandatory
      security.protocol: "SASL_SSL",
      sasl.mechanisms: "SCRAM-SHA-256",

      #mandatory
      sasl.username: "",
      #mandatory
      sasl.password: "",

      ssl.cipher.suites: "",
      ssl.curves.list: "",
      ssl.sigalgs.list: "",
      ssl.key.location: "",
      ssl.key.password: "",
      ssl.key.pem: "",
    }
  # spell-checker:enable
dynaconf_merge: true
