name: Execute Tests
description: Execute all tests
inputs:
  module:
    description: 'the actual module on which the tests should run. "."  for all modules'
    required: True
    default: "."
  integration_tests:
    description: "Boolean, If True all tests should run. If False skip tests tagged for integration"
    required: False
    default: "false"
  test_by_directory:
    description: "Boolean, If True tests are run directory by directory. This is done to reduce memory consumption on large test suites."
    required: False
    default: "false"
  pytest_flags:
    description: "String, additional flags to be passed to pytest while running tests"
    required: False
    default: ""
  SAFETY_API_KEY:
    description: "API Key to invoke safety scanner. see https://safetycli.com/"
    required: True

runs:
  using: "composite"
  steps:
    - name: Lint with ruff
      shell: bash
      run: |
        # change to current directory of module        
        cd ./${{ inputs.module }} 
        # stop the build if there are Python syntax errors or undefined names
        uv tool run ruff check --output-format=github  --select=E9,F63,F7,F82  .
        # exit-zero treats all errors as warnings. report all other errors but don't fail the job
        uv tool run ruff check --output-format=github --exit-zero .

    - name: Test with pytest
      shell: bash
      run: |
        # change to current directory of module            
        cd ./${{ inputs.module }}
        if [[ ${RUNNER_DEBUG} == 1 ]] ; then
          PYTEST_CMD="uv run pytest --debug ${{inputs.pytest_flags}} "
        else
          PYTEST_CMD="uv run pytest ${{inputs.pytest_flags}}"
        fi

        if ${{ inputs.test_by_directory }} ; then
          # Execute tests directory by directory
          for d in $(find test -type d -exec sh -c 'ls -1 "$1"/*.py >/dev/null 2>&1 && echo "$1"' _ {} \;) ; do
            if ls "$d"/test_*.py >/dev/null 2>&1 ; then
              echo "------------------------------------------"
              echo "Running tests in directory: $d"
              if ! ${{ inputs.integration_tests }} ; then
                $PYTEST_CMD -m 'not integrationtest' "$d"/*.py
              else
                $PYTEST_CMD "$d"/*.py
              fi
              if [ $? -ne 0 ]; then
                  echo "Tests failed in $d. Stopping."
                  exit 1
              fi
              echo "------------------------------------------"
              echo ""
            fi
          done
        else
          # Execute all tests together
          if ! ${{ inputs.integration_tests }} ; then
            $PYTEST_CMD -m 'not integrationtest'
          else
            $PYTEST_CMD
          fi
        fi

    - name: Run Safety CLI to check for vulnerabilities
      uses: pyupio/safety-action@v1
      with:
        api-key: ${{ inputs.SAFETY_API_KEY }}
        args: --target ./${{ inputs.module }} --policy-file ./.safety-policy.yml
