name: Execute Tests

inputs:
    module:
        description: 'the actual module on which the tests should run. "" empty for all modules'

    integration_tests:
        description: "Boolean, If True all tests should run. If False skip tests tagged for integration"
        required: false
        default: false
steps:
    - name: Test with pytest
      run: |
          # change to current directory of module            
          cd ./${{ inputs.module }}
          if $integration_tests ; then
              poetry run pytest 
          else 
              poetry run pytest -m "not integrationtest"

    - name: Test for security vulnerabilities
      run: |
          # change to current directory of module        
          cd ./${{ inputs.module }} 
          poetry run safety check
