name: Setup Python Environment, dependencies and static checks
inputs:
    module:
        description: 'the actual module on which the tests should run. "" i.e empty for all modules'

steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
        run: |
          # change to current directory of module        
          cd ${{ inputs.module }} 
          python -m pip install --upgrade pip poetry
          poetry install

    - name: Lint with ruff
        run: |
          # change to current directory of module        
          cd ${{ inputs.module }} 
          # stop the build if there are Python syntax errors or undefined names
          poetry run ruff check  . --output-format=github --exit-zero

    - name: Test for security vulnerabilities
        run: |
          # change to current directory of module        
          cd ${{ inputs.module }}  
          poetry run safety check