[tool.poetry]
name = "uns_spb_mapper"
version = "0.7.10"
description = "SparkplugB decoder to parse and unpack  SparkplugB messages to the UNS structure"
license = "MIT"
authors = ["Ashwin Krishnan <mkashwin@gmail.com>"]
maintainers = [
    "Himanshu Dhami <himanshudhami@gmail.com>",
    "Johan Jeppson <logic4human@gmail.com>",
]
readme = "README.md"
# homepage = ""
repository = "https://github.com/mkashwin/unifiednamespace/tree/main/05_sparkplugb"
# documentation = ""
keywords = ["uns", "mqtt", "sparkplugb"]
#classifiers = [
#   "License :: OSI Approved :: MIT License",
#   "Intended Audience :: Manufacturing",
#   "Operating System :: OS Independent",
#   "Topic :: Software Development :: Libraries :: spB to UNS ",
#   "Topic :: Industry 4.0 :: Unified Name Space :: spB to UNS Mapper Client"
# ]
packages = [{ include = "uns_spb_mapper", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
logger = "^1.4"
dynaconf = "^3.2.4"


[tool.poetry.group.dev.dependencies]
uns-mqtt = { path = "../02_mqtt-cluster", develop = true }

[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"
yapf = "^0.40.2"
flake8 = "^6.1.0"
pytest-cov = "^4.1.0"
safety = "^2.3.5"
pylint = "^3.0.3"

[tool.poetry.scripts]
uns_spb_mapper = "uns_spb_mapper.uns_sparkplugb_listener:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
norecursedirs = [".git", "build", "node_modules", "env*", "tmp*"]
testpaths = ["test"]
markers = ["integrationtest: mark a test as an integration test"]


[tool.pylint.main]
# Files or directories to be skipped. They should be base names, not paths.
ignore = [
    ".git",
    "generated",
    ".github",
    "__pycache__",
    "*env*",
    "build",
    "dist",
]

[tool.pylint.format]
# Maximum number of characters on a single line.
max-line-length = 127
