name: Installs librdkafka
description: Installs librdkafka

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/pyproject.toml
          **/uv.lock
    - name: Install librdkafka
      shell: bash
      run: |
        LIBRDKAFKA_VER="2.12.1"
        # Need to install https://github.com/confluentinc/librdkafka/releases/tag/v${LIBRDKAFKA_VER} as alpine does not have this version
        wget -q https://github.com/confluentinc/librdkafka/archive/refs/tags/v"${LIBRDKAFKA_VER}".zip
        unzip -o v"${LIBRDKAFKA_VER}".zip
        # trunk-ignore(shellcheck/SC2164)
        cd librdkafka-"${LIBRDKAFKA_VER}"
        sudo bash -c "./configure --install-deps --disable-gssapi --disable-lz4-ext --enable-static
            ./configure --prefix /usr && \
            make && \
            make install"
        cd .. &&
          rm v"${LIBRDKAFKA_VER}".zip &&
          rm -rf librdkafka-"${LIBRDKAFKA_VER}"
    # 1.1 setup the python environment
