name: Update Version and Build Docker Image

on:
  push:
    branches:
      - main
    paths:
      - version.txt
  workflow_dispatch:

env:
  SHA_TAG: ${{ env.GITHUB_SHA }}
  MODULES: |
    03_uns_graphdb
    04_uns_historian
    05_sparkplugb
  IMAGE_NAMES: |
    uns/graphdb
    uns/historian
    uns/spb_mapper
jobs:
  update-version:
    name: Update version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version.txt
        id: read_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Update version in pyproject.toml
        run: |
          echo "Updating all pyproject.toml with version ${{ env.VERSION }}"
          find . -name 'pyproject.toml' -type f -exec sed -i "s/^version.*/version = \"${{ env.VERSION }}\"/g" {} +
      - name: Commit and push modified files
        uses: actions/github-script@0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            git config --global user.email "actions@github.com"
            git config --global user.name "Github Actions"
            git add .
            git commit -m "Update version number to ${{ env.VERSION }}"
            git push origin main
