# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UNS All Modules

on:
  push:
    branches:
      - "**"
    paths:
      - "**/*.py"
      - "**/pyproject.toml"
      - "**/poetry.lock"
      - ".github/workflows/*.yml"
      - ".github/include/**"

  pull_request:
    branches:
      - "**"
    paths:
      - "**/*.py"
      - "**/pyproject.toml"
      - "**/poetry.lock"
      - ".github/workflows/*.yml"
      - ".github/include/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        module:
          [
            "./02_mqtt-cluster",
            "./03_uns_graphdb",
            "./04_uns_historian",
            "./05_sparkplugb",
            "./06_uns_kafka",
            "./07_uns_graphql",
          ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup with python environment
        uses: ./.github/include/setup_python/
        with:
          module: ${{ matrix.module }}

      - name: Run all type of tests
        uses: ./.github/include/execute_tests/
        with:
          module: ${{ matrix.module }}
          integration_tests: false
