# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UNS All Modules

on:
  push:
    branches:
      - "**"
    paths:
      - "**/*.py"
      - "**/pyproject.toml"
      - "**/uv.lock"
      - ".github/workflows/*.yml"
      - ".github/include/**"

  pull_request:
    branches:
      - "**"
    paths:
      - "**/*.py"
      - "**/pyproject.toml"
      - "**/uv.lock"
      - ".github/workflows/*.yml"
      - ".github/include/**"
  workflow_dispatch:
    inputs:
      pytest_add_opts: # trunk-ignore(checkov/CKV_GHA_7) # trunk-ignore(checkov/CKV_GHA_7)
        description: "additional pytest options"
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        module:
          [
            "./02_mqtt-cluster",
            "./03_uns_graphdb",
            "./04_uns_historian",
            "./05_sparkplugb",
            "./06_uns_kafka",
            "./07_uns_graphql",
          ]
    steps:
      - uses: actions/checkout@v5

      - name: install librdkafka
        uses: ./.github/include/setup_librdkafka/
        if: ${{ (matrix.module =='./06_uns_kafka') || (matrix.module =='./07_uns_graphql') }}

      - name: Setup with python environment
        uses: ./.github/include/setup_python/
        with:
          module: ${{ matrix.module }}

      - name: Run all type of tests
        uses: ./.github/include/execute_tests/
        with:
          module: ${{ matrix.module }}
          integration_tests: false
          SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
          pytest_flags: ${{ inputs.pytest_add_opts }}
