# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UNS Graph DB MQTT Client

on:
  push:
    branches:
      - "**"
    paths:
      - "02_mqtt-cluster/**"
      - "03_uns_graphdb/**"
      - ".github/workflows/uns_graphdb-app.yml"
  pull_request:
    branches:
      - "**"
    paths:
      - "02_mqtt-cluster/**"
      - "03_uns_graphdb/**"
      - ".github/workflows/uns_graphdb-app.yml"
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry shell 
          poetry install

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./03_uns_graphdb/src ./03_uns_graphdb/test --count --select=E9,F63,F7,F82 --show-source --statistics 
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 ./03_uns_graphdb/src ./03_uns_graphdb/test --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        env:
          UNS_graphdb.url: ${{ secrets.NEO4J_URL }}
          UNS_graphdb.username: ${{ secrets.NEO4J_USER }}
          UNS_graphdb.password: ${{ secrets.NEO4J_PWD }}
        run: |
          pytest -m "not integrationtest" ./03_uns_graphdb/test/
