# This workflow generate the SBOM for the unified namespace project.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UNS SBOM ( Software Bill of Materials )
on:
  push:
    branches:
      - "**"
    paths:
      - "**/src/**"
      - "**/test/**"
      - "**/*.sh"
  pull_request:
    branches:
      - "**"
    paths:
      - "**/src/**"
      - "**/test/**"
      - "**/*.sh"
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Generate Software Bill of Material for UNS
        uses: CycloneDX/gh-python-generate-sbom@v1.0.1
        with:
          input: "**/requirements.txt **/requirements_dev.txt"
          output: "./sbom.xml"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "./sbom.xml"
