# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UNS MQTT Module

on:
  push:
    branches:
      - "**"
    paths:
      - "02_mqtt-cluster/**/*.py"
      - "02_mqtt-cluster/pyproject.toml"
      - "02_mqtt-cluster/poetry.lock"
      - ".github/workflows/uns_mqtt-app.yml"
  pull_request:
    branches:
      - "**"
    paths:
      - "02_mqtt-cluster/**/*.py"
      - "02_mqtt-cluster/pyproject.toml"
      - "02_mqtt-cluster/poetry.lock"
      - ".github/workflows/uns_mqtt-app.yml"
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Setup with python environment
        uses: ./.github/include/setup_python/
        with:
          module: 02_mqtt-cluster

      - name: Run all type of tests
        uses: ./.github/include/execute_tests/
        with:
          module: 02_mqtt-cluster
          integration_tests: true
