# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UNS Kafka Mapper

on:
  push:
    branches:
      - "**"
    paths:
      - "02_mqtt-cluster/**/*.py"
      - "02_mqtt-cluster/pyproject.toml"
      - "02_mqtt-cluster/poetry.lock"
      - "06_uns_kafka/**/*.py"
      - "06_uns_kafka/pyproject.toml"
      - "06_uns_kafka/poetry.lock"
      - "06_uns_kafka/Dockerfile"
      - ".github/workflows/uns_kafka-app.yml"
      - ".github/include/**"

  pull_request:
    branches:
      - "**"
    paths:
      - "02_mqtt-cluster/**/*.py"
      - "02_mqtt-cluster/pyproject.toml"
      - "02_mqtt-cluster/poetry.lock"
      - "06_uns_kafka/**/*.py"
      - "06_uns_kafka/pyproject.toml"
      - "06_uns_kafka/poetry.lock"
      - "06_uns_kafka/Dockerfile"
      - ".github/workflows/uns_kafka-app.yml"
      - ".github/include/**"

permissions:
  contents: read

jobs:
  build_code:
    runs-on: ubuntu-latest
    env:
      UNS_mqtt.host: "localhost"
      UNS_mqtt.port: 1883
      UNS_kafka.config: "{ 'client.id' = 'uns_kafka_client', 'bootstrap.servers' ='localhost:9092' }"
    services:
      uns_mqtt:
        image: emqx/emqx:latest
        ports:
          - "1883:1883"
          - "8083:8083"
      uns_kafka:
        image: bitnami/kafka:latest
        ports:
          - "9092:9092"
        env:
          ALLOW_PLAINTEXT_LISTENER: "yes"
          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
          KAFKA_CFG_NODE_ID: 0
          KAFKA_CFG_PROCESS_ROLES: controller,broker
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@uns_kafka:9093
          KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

    steps:
      - uses: actions/checkout@v4

      - name: Setup with python environment
        uses: ./.github/include/setup_python/
        with:
          module: 06_uns_kafka

      - name: Run all type of tests
        uses: ./.github/include/execute_tests/
        with:
          module: 06_uns_kafka
          integration_tests: true
          SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}

  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile and Test Dockerfile
        uses: ./.github/include/test_docker_builds/
        with:
          module: 06_uns_kafka
          image_name: uns/kafka_mapper
