# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UNS MQTT Module

on:
  push:
    branches:
      - "**"
    paths:
      - "02_mqtt-cluster/**/*.py"
      - "02_mqtt-cluster/pyproject.toml"
      - "02_mqtt-cluster/poetry.lock"
      - ".github/workflows/uns_mqtt-app.yml"
  pull_request:
    branches:
      - "**"
    paths:
      - "02_mqtt-cluster/**/*.py"
      - "02_mqtt-cluster/pyproject.toml"
      - "02_mqtt-cluster/poetry.lock"
      - ".github/workflows/uns_mqtt-app.yml"
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          cd ./02_mqtt-cluster
          python -m pip install --upgrade pip poetry
          poetry install

      - name: Lint with ruff
        run: |
          # change to current directory of module        
          cd ./02_mqtt-cluster 
          # stop the build if there are Python syntax errors or undefined names
          poetry run ruff check  . --output-format=github --exit-zero

      - name: Test for security vulnerabilities
        run: |
          cd ./02_mqtt-cluster   
          poetry run safety check

      - name: Test with pytest
        run: |
          # change to current directory of module        
          cd ./02_mqtt-cluster  
          poetry run pytest ./test/
