# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UNS MQTT Module

on:
  push:
    branches:
      - "**"
    paths:
      - "02_mqtt-cluster/**/*.py*"
      - "02_mqtt-cluster/pyproject.toml"
      - "02_mqtt-cluster/uv.lock"
      - ".github/workflows/uns_mqtt-app.yml"
      - ".github/include/**"

  pull_request:
    branches:
      - "**"
    paths:
      - "02_mqtt-cluster/**/*.py*"
      - "02_mqtt-cluster/pyproject.toml"
      - "02_mqtt-cluster/uv.lock"
      - ".github/workflows/uns_mqtt-app.yml"
      - ".github/include/**"

  workflow_dispatch:
    inputs:
      pytest_add_opts: # trunk-ignore(checkov/CKV_GHA_7) # trunk-ignore(checkov/CKV_GHA_7)
        description: "additional pytest options"
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v5

      - name: Setup with python environment
        uses: ./.github/include/setup_python/
        with:
          module: 02_mqtt-cluster

      - name: Setup MQTT Broker for Integration Tests
        shell: bash
        run: |
          cd ./02_mqtt-cluster/test/local_mqtt
          docker compose  -f mosquitto_docker-compose.yml up -d --wait

      - name: Run all type of tests
        uses: ./.github/include/execute_tests/
        with:
          module: 02_mqtt-cluster
          integration_tests: true
          SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
          pytest_flags: ${{ inputs.pytest_add_opts }}

      - name: Shutdown  MQTT Broker for Integration Tests
        shell: bash
        run: |
          cd ./02_mqtt-cluster/test/local_mqtt
          docker compose  -f mosquitto_docker-compose.yml down
